apiVersion: v1
kind: Secret
metadata:
  name: scala-crawler-secrets
  namespace: scala-crawler
type: Opaque
stringData:
  CONTROL_PLANE_DB_PASSWORD: "scala_crawler"
  POSTGRES_PASSWORD: "scala_crawler"
