akka {
  loglevel = "INFO"
  http.server.preview.enable-http2 = off
}

control-plane {
  http {
    host = "0.0.0.0"
    host = ${?CONTROL_PLANE_HTTP_HOST}
    port = 8080
    port = ${?CONTROL_PLANE_HTTP_PORT}
  }

  db {
    url = "jdbc:postgresql://localhost:5432/scala_crawler"
    url = ${?CONTROL_PLANE_DB_URL}
    user = "scala_crawler"
    user = ${?CONTROL_PLANE_DB_USER}
    password = "scala_crawler"
    password = ${?CONTROL_PLANE_DB_PASSWORD}
  }
}
