apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scala-crawler-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lechuhuuha/scala-crawler.git
    targetRevision: HEAD
    path: deploy/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: scala-crawler
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
